### ISSUE TITLE
"Hello World!" - Example is not working as intended

### ISSUE THREAD

**Issue by Vyperus** [process-engine/documentation#1]
#### Describe your issue

"Hello World!" - Example (https://processenginejs.github.io/documentation/quick-start/hands-on/hello-world.html) is not working. I can create and start the process but it won't be displayed after i clicked on "Start".

#### How can others reproduce the issue?

Just follow the steps in the "Hello World!"-Example exactly as they are mentioned there.

#### Possible solution

The solution is to add the "role" "guest" to the lane. However this is not mentioned in the Example.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ppoetschke** [comment]
This is related to https://github.com/process-engine/process_engine/issues/8

**Comment by cmg-dev** [comment]
@Vyperus Wie ist der stand hier?
