### ISSUE TITLE
💬 "Sie" oder "Du" in der Doku?

### ISSUE THREAD

**Issue by Vyperus** [process-engine/documentation#13]
Sollen wir den Leser, in der Getting Started Dokumentation, mit "Sie" oder "Du" ansprechen?

Beispiel:

`Stellen Sie sich vor, Sie möchten einen anderen Port zum Hosten der Anwendung verwenden.`

oder

`Stell dir vor, du möchtest eine anderen Port zum Hosten der Anwendung verwenden.`

**Comment by ppoetschke** [comment]
Ich bin für "Sie", da bei der Zielgruppe im professionellen Umfeld so üblich. Selbst die Schweden verwenden Du nur im B2C-Bereich, nicht bei B2B.

**Comment by cmg-dev** [comment]
**1. Sie/Du können gänzlich vermeiden werden**

   Ich denke eine Dokumentation kann so geschrieben werden, dass man
   neutral formuliert und nicht direkt adressiert. Das sollte mMn reichen.

**2. Sollte das nicht möglich sein, bin ich für das Du.**

   Allein weil viel Dokumentation so geschrieben ist aktuell.

**Comment by cmg-dev** [comment]
> Beispiel:
>
> Stellen Sie sich vor, Sie möchten einen anderen Port zum Hosten der Anwendung verwenden.
>
> oder
>
> Stell dir vor, du möchtest eine anderen Port zum Hosten der Anwendung verwenden.

Beide Formulierungen würde ich ablehnen.

Ich würde schreiben:

**Problem**

Port zum Hosten der Anwendung ändern.

**Lösung**

(...)

--- 

@Vyperus 
Überlegt bitte IMMER folgendes: "wie würde ich danach Googlen".

Und formuliert die technischen Texte so.

**Comment by cmg-dev** [comment]
@all für mich ist das damit erledigt.

kann das dann zu?

**Comment by Vyperus** [comment]
Ich denke ja.
