### ISSUE TITLE
Artikel: Beschreibung der Dialoge

### ISSUE THREAD

**Issue by Vyperus** [process-engine/documentation#17]
Beschreibe die Dialoge in der aktuellen Version des BPMN-Studios in einem Artikel für die neue "Getting-Started"-Doku.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by heikomat** [comment]
Das ist in #25 implementiert
