### ISSUE TITLE
Update samples that make use of conditional SequenceFlows

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/documentation#177]
#### Describe your issue

With the implementation of the dynamic UI components, we have fixed an issue where UserTask FormField values were always converted into a string.

As a consequence, all SequenceFlows that make use of conditions such as

`token.history.someField == 'true'` 

must have their condition changed to

`token.history.someField == true` 

Same goes for numbers.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by LeoTT** [comment]
Only appearance of that problem in the examples is in the sendmail example. Will have to delete that example because the MailService does no longer exist.
There are other SequenceFlows with conditions, but none of them following UserTasks.
