### ISSUE TITLE
"Consuming a REST API"-Example ist not working as intended

### ISSUE THREAD

**Issue by Vyperus** [process-engine/documentation#2]
#### Describe your issue

When I try to do the "Consuming a REST API"-Example (https://processenginejs.github.io/documentation/quick-start/hands-on/consuming-rest-api.html)
I'm not able to show the received Data. 
I followed the steps exactly like they are mentioned in the example, but when i click on "start" to process stops at the "User Task" but doesn't show any Data as expected.
The problem lies within the Function that handles the Data from the REST API.

#### How can others reproduce the issue?

Just follow the steps in the Example exactly like they are mentioned

#### Possible solution

"Charon" is handling the values of the "uiConfig" differently than the package "Process-Engine".
The correct way: https://github.com/process-engine/process_engine/blob/35a55fb0402f649efad245974646a0b687df0900/src/entity_types/node_instance.ts#L657
The not-so correct way (in Charon): https://github.com/process-engine/charon/blob/2dff0a599a17298170eb39f7140d677eb56f01da/src/modules/dynamic-ui/dynamic-ui.service.ts#L136

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by heikomat** [comment]
This is a charon-problem. I cloned the issue here: https://github.com/process-engine/charon/issues/12
