### ISSUE TITLE
Artikel: BPMN -> Beispiel Prozesse

### ISSUE THREAD

**Issue by alexanderkasten** [process-engine/documentation#45]
#### Describe your issue

Beschreibe Beispiel Prozesse in einem Artikel für die "Getting-Started"-Doku.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by cmg-dev** [comment]
@LeoTT Kannst du das Issue bitte updaten um zu zeigen, welche Beispiel-Prozesse du erstellen willst?

Ich glaube auch, dass viele Issues schon Beispiel-Prozesse beschreiben, aber nicht hier verlinkt sind. Kannst du das bitte auch machen?

**Comment by LeoTT** [comment]
Hier ein paar Ideen.


| Beispiel                       | Prozessbeschreibung                                                                                                                                                | BPMN-Aspekte                | technische Aspekte                   |
|--------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------|--------------------------------------|
| Chatbot(Eliza/Psychotherapeut) | Nutzer gibt Frage oder Aussage ein -> Chatbot gibt Antwort -> Neustart                                                                                             | Pools, Events               | uiWidget Form, uiWidget Alert, REST  |
| Pizzeria                       | Zutaten werden ausgesucht (auf Webseite) -> Bestellung wird abgeschickt -> Kunde erhält Bestätigung (auf Webseite)                                                 | Pools, Lanes, Events        | Webseite, REST                       |
| Wohnungsvermittlung            | Kunde gibt Anforderungen(Größe, Anzahl Zimmer, etc) Webseite ein -> Anforderungen werden mit Datenbank voller Wohnungen verglichen -> Mail wird an Kunden versandt | Pools, Events, Service Task | uiWidget Form, Datenbank, REST, Mail |


Erstes Beispiel funktioniert allein im Rahmen von Charon. Nachteil
ist, dass es nicht praxisnah ist. Implementation ist aber leicht
und es ist anschaulich.

Die anderen beiden Beispiele sollen möglichst viele technische Ebenen
ansprechen und etwas realistischer sein.

Ich vermisse noch ein Beispiel für Parametrierung (#19).

Bin dankbar für jeden Tipp und Vorschlag.
