### ISSUE TITLE
Artikel: Integration -> ConsumerClientAPI -> Ziel und Aufgabe

### ISSUE THREAD

**Issue by alexanderkasten** [process-engine/documentation#48]
#### Describe your issue

Beschreibe die Ziele und Aufgaben in einem Artikel für die "Getting-Started"-Doku.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [ ] I've checked if this issue already exists
- [ ] I've included all the information that i think is relevant
- [ ] I've added logs and/or screenshots (if applicable)
- [ ] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
This has become obsolete. There is no more `ConsumerClientAPI` like there was back then.
