### ISSUE TITLE
👷🚀 How to deploy the documentation

### ISSUE THREAD

**Issue by alexanderkasten** [process-engine/documentation#74]
#### Describe your issue

Es soll dokumentiert werden, wie die Dokumentation fertig gebaut werden kann und anschließend auf 
process-engine.io/documentation online gebracht wird.
Eventuell kann auch die Jenkinsfile angepasst werden, damit das Deployen automatisch geschieht.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [ ] I've checked if this issue already exists
- [ ] I've included all the information that i think is relevant
- [ ] I've added logs and/or screenshots (if applicable)
- [ ] I've mentioned PRs and issues that relate to this one

**Comment by Paulomart** [comment]
Ich weißt selbst nicht, wie die aktuelle Dokumentation deployed ist. Vermutlich mit GitHub Pages? Außerdem scheint die oben geannte URL `http://process-engine.io/documentation/` nicht zu funktionieren, es fehlt das `www.`, dann kommt man auch zu Dokumentation.

**Comment by alexanderkasten** [comment]
Ich habe die Documentation wie folgt deployed:

```
# make the gh-pages-branch be identical to develop
git checkout gh-pages
git pull
git checkout develop
git pull
git merge --strategy=ours gh-pages
git checkout gh-pages
git merge develop

# install the necessary dependencies to build the gitbook
npm install

# build the gitbook
./node_modules/.bin/gitbook build

# make the root contain only the built gitbook and nothing else
TEMP_DIR=$(mktemp -d)
mv ./* $TEMP_DIR/
mv $TEMP_DIR/_book/* ./
rm -rf $TEMP_DIR

git add -A
git commit -m "<COMMIT MESSAGE>"
git push
```
Ich werde das aktuelle build_prod.sh script anpassen, da es aktuell nicht funktioniert.

@Paulomart
