### ISSUE TITLE
Add a user manual for the consumer api

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/documentation#87]
#### Describe your issue

We need a descriptive user manual for the consumer api.

Most importantly, this needs to be a "How-To" Guide for the enduser, **not** a technical implementation description.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
https://github.com/process-engine-pro/organization/issues/132

**Comment by ElRaptorus** [comment]
https://github.com/process-engine-pro/organization/issues/140

**Comment by ElRaptorus** [comment]
https://github.com/process-engine-pro/organization/issues/140

**Comment by roblen45** [comment]
#170
