### ISSUE TITLE
🍱 Update Screenshots of bpmn-studio

### ISSUE THREAD

**Issue by Paulomart** [process-engine/documentation#88]
#### Describe your issue

Currently there are a lot of screenshots of bpmn-studio that are outdated.

#### How can others reproduce the issue?

See this for example https://github.com/process-engine/documentation/blob/d9e8f556c56211c7a3ab272a9231e0c873b7ee84/bpmn-studio/task-list.png

#### Possible solution

Update the screenshots

- by hand :(
- find something to automate this :)

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
https://github.com/process-engine-pro/organization/issues/88

**Comment by ElRaptorus** [comment]
https://github.com/process-engine-pro/organization/issues/161
